### ISSUE TITLE
Need support .NET Framework 4.5.1

### ISSUE THREAD

**Issue by peter0121** [sskodje/wpfchrometabs-mvvm#13]
I use the MVVM Light tool box create project (WPF451)
and download with NuGet
but click the top add button can't work .
.NET Framework 4.5.1 + MVVM Light 5.2.0

So i try to change demo code , .NET Framework 4 -> .NET Framework 4.5.1
MVVM Light 5.2.0
i got the same problem.

**Comment by sskodje** [comment]
Hello!
Thank you for reporting this issue! I managed to recreate it, and it happens because the AddTabCommand's CanExecute event is not raised when the control is created, so the button is never enabled.

I have updated the source and NuGet with the fix, let me know if you still have problems after updating,

**Comment by peter0121** [comment]
It works , nice job !
thanks
